// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BridgeConfig {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "BridgeType", tag = "2")]
    pub r#type: i32,
    #[prost(bool, tag = "3")]
    pub enabled: bool,
    #[prost(oneof = "bridge_config::Config", tags = "10")]
    pub config: ::core::option::Option<bridge_config::Config>,
}
/// Nested message and enum types in `BridgeConfig`.
pub mod bridge_config {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Config {
        #[prost(message, tag = "10")]
        Jwt(super::JwtBridgeConfig),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JwtBridgeConfig {
    #[prost(string, tag = "1")]
    pub wellknown_url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub issuer: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub audiences: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub mapping: ::core::option::Option<MappingConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MappingConfig {
    #[prost(string, tag = "1")]
    pub subject_claim: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub organization_claim: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub custom: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// List
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListBridgesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBridgesResponse {
    #[prost(message, repeated, tag = "1")]
    pub bridges: ::prost::alloc::vec::Vec<BridgeConfig>,
}
/// Get
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBridgeRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBridgeResponse {
    #[prost(message, optional, tag = "1")]
    pub bridge: ::core::option::Option<BridgeConfig>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Add
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddBridgeRequest {
    #[prost(message, optional, tag = "1")]
    pub bridge: ::core::option::Option<BridgeConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddBridgeResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Update
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateBridgeRequest {
    #[prost(message, optional, tag = "1")]
    pub bridge: ::core::option::Option<BridgeConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateBridgeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Remove
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveBridgeRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveBridgeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Bridge Types
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BridgeType {
    Unspecified = 0,
    Jwt = 1,
    /// Future
    Spiffe = 2,
    /// Future
    Vc = 3,
}
impl BridgeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BRIDGE_TYPE_UNSPECIFIED",
            Self::Jwt => "BRIDGE_TYPE_JWT",
            Self::Spiffe => "BRIDGE_TYPE_SPIFFE",
            Self::Vc => "BRIDGE_TYPE_VC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BRIDGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "BRIDGE_TYPE_JWT" => Some(Self::Jwt),
            "BRIDGE_TYPE_SPIFFE" => Some(Self::Spiffe),
            "BRIDGE_TYPE_VC" => Some(Self::Vc),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod bridge_admin_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BridgeAdminServiceServer.
    #[async_trait]
    pub trait BridgeAdminService: std::marker::Send + std::marker::Sync + 'static {
        /// List all configured bridges
        async fn list_bridges(
            &self,
            request: tonic::Request<super::ListBridgesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBridgesResponse>,
            tonic::Status,
        >;
        /// Get a specific bridge configuration
        async fn get_bridge(
            &self,
            request: tonic::Request<super::GetBridgeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBridgeResponse>,
            tonic::Status,
        >;
        /// Add a new bridge configuration
        async fn add_bridge(
            &self,
            request: tonic::Request<super::AddBridgeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddBridgeResponse>,
            tonic::Status,
        >;
        /// Update an existing bridge configuration
        async fn update_bridge(
            &self,
            request: tonic::Request<super::UpdateBridgeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateBridgeResponse>,
            tonic::Status,
        >;
        /// Remove a bridge configuration
        async fn remove_bridge(
            &self,
            request: tonic::Request<super::RemoveBridgeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveBridgeResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct BridgeAdminServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BridgeAdminServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BridgeAdminServiceServer<T>
    where
        T: BridgeAdminService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/permguard.trustplane.bridge_admin.v1.BridgeAdminService/ListBridges" => {
                    #[allow(non_camel_case_types)]
                    struct ListBridgesSvc<T: BridgeAdminService>(pub Arc<T>);
                    impl<
                        T: BridgeAdminService,
                    > tonic::server::UnaryService<super::ListBridgesRequest>
                    for ListBridgesSvc<T> {
                        type Response = super::ListBridgesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListBridgesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BridgeAdminService>::list_bridges(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListBridgesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/permguard.trustplane.bridge_admin.v1.BridgeAdminService/GetBridge" => {
                    #[allow(non_camel_case_types)]
                    struct GetBridgeSvc<T: BridgeAdminService>(pub Arc<T>);
                    impl<
                        T: BridgeAdminService,
                    > tonic::server::UnaryService<super::GetBridgeRequest>
                    for GetBridgeSvc<T> {
                        type Response = super::GetBridgeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBridgeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BridgeAdminService>::get_bridge(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBridgeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/permguard.trustplane.bridge_admin.v1.BridgeAdminService/AddBridge" => {
                    #[allow(non_camel_case_types)]
                    struct AddBridgeSvc<T: BridgeAdminService>(pub Arc<T>);
                    impl<
                        T: BridgeAdminService,
                    > tonic::server::UnaryService<super::AddBridgeRequest>
                    for AddBridgeSvc<T> {
                        type Response = super::AddBridgeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddBridgeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BridgeAdminService>::add_bridge(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddBridgeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/permguard.trustplane.bridge_admin.v1.BridgeAdminService/UpdateBridge" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateBridgeSvc<T: BridgeAdminService>(pub Arc<T>);
                    impl<
                        T: BridgeAdminService,
                    > tonic::server::UnaryService<super::UpdateBridgeRequest>
                    for UpdateBridgeSvc<T> {
                        type Response = super::UpdateBridgeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateBridgeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BridgeAdminService>::update_bridge(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateBridgeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/permguard.trustplane.bridge_admin.v1.BridgeAdminService/RemoveBridge" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveBridgeSvc<T: BridgeAdminService>(pub Arc<T>);
                    impl<
                        T: BridgeAdminService,
                    > tonic::server::UnaryService<super::RemoveBridgeRequest>
                    for RemoveBridgeSvc<T> {
                        type Response = super::RemoveBridgeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveBridgeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BridgeAdminService>::remove_bridge(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveBridgeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BridgeAdminServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "permguard.trustplane.bridge_admin.v1.BridgeAdminService";
    impl<T> tonic::server::NamedService for BridgeAdminServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
